name: PacketLogger
main: com.sainttx.packetlogger.PacketLoggerPlugin
version: ${project.version}
depend: [ ProtocolLib ]

commands:
  packets:
    description: Manage the interception of player packet logs
    permission: packetlogger.manage
    permission-message: "You do not have permission to use this command"
    usage: |
           Manage the interception of player packet logs
           /<command> <log|clear|dump> <player>

permissions:
  packetlogger.manage:
    default: op
    description: Grants access to the /packets command